// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TnR_SS.Entity.Models;

namespace TnR_SS.Entity.Migrations
{
    [DbContext(typeof(TnR_SSContext))]
    [Migration("20210531013007_addFirstValue")]
    partial class addFirstValue
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Latin1_General_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TnR_SS.Entity.Models.RoleUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("RoleUser");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "Admin",
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "Trader",
                            RoleName = "Trader"
                        },
                        new
                        {
                            Id = 3,
                            DisplayName = "Weight Recorder",
                            RoleName = "Weight Recorder"
                        });
                });

            modelBuilder.Entity("TnR_SS.Entity.Models.UserInfor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Avatar")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("DOB");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdentifyCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<string>("SaltPassword")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Id", "PhoneNumber" }, "UC_PhoneNumber")
                        .IsUnique();

                    b.HasIndex(new[] { "PhoneNumber" }, "UQ_PhoneNumber")
                        .IsUnique();

                    b.ToTable("UserInfor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2021, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Nguyen",
                            IdentifyCode = "123456789",
                            Lastname = "Quan",
                            Password = "1a56be4be3e34472001aa7e5f5fc5cbe84428edfe902bdf1508fcf33ff517198",
                            PhoneNumber = "0966848112",
                            RoleId = 2,
                            SaltPassword = "qwertyuiopasdfghjklz"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2021, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Anh",
                            IdentifyCode = "123456789",
                            Lastname = "Duc",
                            Password = "1a56be4be3e34472001aa7e5f5fc5cbe84428edfe902bdf1508fcf33ff517198",
                            PhoneNumber = "0969360445",
                            RoleId = 3,
                            SaltPassword = "qwertyuiopasdfghjklz"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2021, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1999, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Admin",
                            IdentifyCode = "123456789",
                            Lastname = "Admin",
                            Password = "f781bfeada73d5d4d703dca8c3b1b0eba6aa49151ac0fcfaa5d10510eaecdfd3",
                            PhoneNumber = "admin",
                            RoleId = 1,
                            SaltPassword = "qwertyuiopasdfghjklz"
                        });
                });

            modelBuilder.Entity("TnR_SS.Entity.Models.UserInfor", b =>
                {
                    b.HasOne("TnR_SS.Entity.Models.RoleUser", "Role")
                        .WithMany("UserInfors")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK__UserInfor__RoleUser")
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TnR_SS.Entity.Models.RoleUser", b =>
                {
                    b.Navigation("UserInfors");
                });
#pragma warning restore 612, 618
        }
    }
}
