pipeline {
    agent any
    environment {
        dotnet = 'path\\to\\dotnet.exe'
    }
    stages {
    	stage('Restore Packages') {
            steps {
                bat "dotnet restore SWP490_G9_PE --configuration Release"
            }
    	}
        stage('Clean') {
            steps {
            bat "dotnet clean"
            }
        }
        stage('Build') {
            steps {
                bat 'dotnet build'
            }
        }   
        stage('Update database') {
            steps {
                bat 'dotnet update-database'
            }
        }
        stage('Publish') {
            steps {
                bat 'dotnet publish -p:PublishProfile=FolderProfile'
            }
        }    
    }
}
