pipeline {
    agent any
    environment {
        dotnet = 'path\\to\\dotnet.exe'
    }
    stages {
    	stage('Restore Packages') {
            steps {
                bat "dotnet restore"
            }
    	}
        stage('Clean') {
            steps {
            bat "dotnet clean"
            }
        }
        stage('Build') {
            steps {
                bat 'dotnet build'
            }
        }   
        stage('Publish') {
            steps {
                bat 'dotnet publish'
            }
        }    
    }
}
